In [1]:
#SET UP
#import sys
#!{sys.executable} -m pip install pandas
#!{sys.executable} -m pip install matplotlib

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from survival import DecayMIRModel

In [3]:
#PROCESS INPUTS
df = pd.read_csv('/home/j/temp/fed1/SEER_case_analysis_formatted_add_unknown_to_other_mortality.csv')

#remove NAs and MIR >1
df = df.dropna()
df = df[df['mi_ratio']<=1]

df['disease_period']=10
df['slope']=-.21

df.head()

,Unnamed: 0,age_group_id,cause_name,cases,deaths,mi_ratio,five_year_cs_survival,five_year_observed_survival,single_year_other_mortality,location_id,other_mortality,year_id,sex_id,acause,disease_period,slope
0,1,1,Acute Lymphocytic Leukemia,6860,327.0,0.047668,0.932799,0.924490,0.003061,102,0.003061,2000-2017,3,Acute Lymphocytic Leukemia,10,-0.21
1,2,1,Acute Monocytic Leukemia,167,52.0,0.311377,0.676647,0.634731,0.023952,102,0.023952,2000-2017,3,Acute Monocytic Leukemia,10,-0.21
2,3,1,Acute Myeloid Leukemia,1092,270.0,0.247253,0.729853,0.691392,0.022894,102,0.022894,2000-2017,3,Acute Myeloid Leukemia,10,-0.21
3,4,1,"Aleukemic, Subleukemic and NOS",56,5.0,0.089286,0.910714,0.821429,0.089286,102,0.089286,2000-2017,3,"Aleukemic, Subleukemic and NOS",10,-0.21
4,5,1,Appendix,3,0.0,0.000000,1.000000,1.000000,0.000000,102,0.000010,2000-2017,3,Appendix,10,-0.21

In [4]:
#RUN MODEL
num_years = 5

model = DecayMIRModel(df['mi_ratio'],
                 df['other_mortality'],
                 df['disease_period'],
                 df['slope'])
model.compute_base_excess_mortality()
survival_rate = model.get_survival_rate(num_years=num_years)

df['base_excess_mortality'] = model.base_excess_mortality
df['abs_survival_rate'] = survival_rate['abs']
df['rel_survival_rate'] = survival_rate['rel']

In [5]:
df.head()

,Unnamed: 0,age_group_id,cause_name,cases,deaths,mi_ratio,five_year_cs_survival,five_year_observed_survival,single_year_other_mortality,location_id,other_mortality,year_id,sex_id,acause,disease_period,slope,base_excess_mortality,abs_survival_rate,rel_survival_rate
0,1,1,Acute Lymphocytic Leukemia,6860,327.0,0.047668,0.932799,0.924490,0.003061,102,0.003061,2000-2017,3,Acute Lymphocytic Leukemia,10,-0.21,0.013509,0.955651,0.967541
1,2,1,Acute Monocytic Leukemia,167,52.0,0.311377,0.676647,0.634731,0.023952,102,0.023952,2000-2017,3,Acute Monocytic Leukemia,10,-0.21,0.107422,0.687590,0.762849
2,3,1,Acute Myeloid Leukemia,1092,270.0,0.247253,0.729853,0.691392,0.022894,102,0.022894,2000-2017,3,Acute Myeloid Leukemia,10,-0.21,0.081882,0.739246,0.815008
3,4,1,"Aleukemic, Subleukemic and NOS",56,5.0,0.089286,0.910714,0.821429,0.089286,102,0.089286,2000-2017,3,"Aleukemic, Subleukemic and NOS",10,-0.21,0.032322,0.630392,0.923641
4,5,1,Appendix,3,0.0,0.000000,1.000000,1.000000,0.000000,102,0.000010,2000-2017,3,Appendix,10,-0.21,0.000000,0.999960,1.000000

In [6]:
#df.to_csv('/home/j/temp/fed1/testing_new_decay_survival_model_outputs_on_case_analysis_data_n=10_m=-.21.csv')